### ISSUE TITLE
BUG: Cannot import GenericURDFFk

### ISSUE THREAD

**Issue by maxspahn** [TomasMerva/gomp#2]
You specify forwardkinematics to be at least 1.1.5 in the `pyproject.toml`. However, the `__init__.py` in forwardkinematics was only extended by the import in v.1.2.0, see history of this file:
https://github.com/maxspahn/forwardKinematics/blob/release/v1.1.5/forwardkinematics/__init__.py

Fix: Update dependency to >=1.2.0.

**Comment by TomasMerva** [comment]
Thank you, its fixed
